channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.12
  - pytorch
  - numpy
  - matplotlib
  - scipy
  - pyyaml
  - pyamrex
  - xarray
  - rasterio
  - pip
  - pip:
    - kintera
    - snapy